name: Automated Previred Scripts

on:
  schedule:
    - cron: "0 5 * * 1-5"  # Lunes a viernes, 14:30 UTC (-3 Chile)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb firefox curl

          # Instalar Microsoft Edge
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

          # Instalar Geckodriver
          wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
          tar -xvzf geckodriver*
          sudo mv geckodriver /usr/local/bin/

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script maestro
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python script_maestro.py
        env:
          PREVIRED_USER: ${{ secrets.PREVIRED_USER }}
          PREVIRED_PASS: ${{ secrets.PREVIRED_PASS }}
          SIGO_USER: ${{ secrets.SIGO_USER }}
          SIGO_PASS: ${{ secrets.SIGO_PASS }}

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: |
            automatizacion.log
            descarga/

      - name: Output Success Message
        run: echo "Script ejecutado correctamente en GitHub Actions."