name: Automated Previred Scripts

on:
  schedule:
    # Lunes (1) a viernes (5), a las 14:30 UTC
    - cron: "0 5 * * 1-5"
  # Opcional: permitir ejecución manual:
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # 1) Descarga tu código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Instala Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Instalar dependencias de sistema
      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Instalar Firefox y un servidor X virtual (xvfb) para Selenium GUI en modo "headless"
          sudo apt-get install -y firefox xvfb

      # 4) Instalar dependencias de Python
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # Ajusta tu requirements.txt
          pip install -r requirements.txt

      # 5) Configurar variables de entorno 
      - name: Set environment
        run: echo "Environment set"
        env:
          PREVIRED_USER: ${{ secrets.PREVIRED_USER }}
          PREVIRED_PASS: ${{ secrets.PREVIRED_PASS }}
          SIGO_USER: ${{ secrets.SIGO_USER }}
          SIGO_PASS: ${{ secrets.SIGO_PASS }}

      # 6) Ejecutar el script maestro
      - name: Run script maestro
        run: python script_maestro.py
        env:
          PREVIRED_USER: ${{ secrets.PREVIRED_USER }}
          PREVIRED_PASS: ${{ secrets.PREVIRED_PASS }}
          SIGO_USER: ${{ secrets.SIGO_USER }}
          SIGO_PASS: ${{ secrets.SIGO_PASS }}

      # 7) Subir logs como artifact
      - name: Subir logs como artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: logs
          path: "*.log"


